default_roles:
  - protofont
  - python
  - system
  - gnome
  - rust
  - go
  - asdf
  - java
  - ssh
  - pass
  - git
  - docker
  - neovim
  - zsh
  - lazygit
  - lazydocker
  - tmux
  - ulauncher
  - obsidian
  - aws
  - scaleway
  - terraform
  - zoxide
  - alacritty
  - eza

theme: catppuccin # choice between: catppuccin only for now. set to "" to skip theme settings
alacritty_version: v0.14.0
neovim_version: v0.11.0
java_version: 17
lazygit_version: v0.41.0
lazydocker_version: v0.23.3

git_user_name: "NicoGGG"
