---
- name: Protofont | Download Proto Font
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/0xProto.zip"
    dest: "/tmp"
    force: true
    mode: "0755"
  register: protofont

- name: Protofont | Set variable protofont_dest
  ansible.builtin.set_fact:
    protofont_dest: "{{ protofont.dest }}"

- name: Protofont | Create font dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share/fonts/"
    state: directory
    recurse: true

- name: Protofont | Unzip Proto font in ~/.local/share/fonts
  ansible.builtin.unarchive:
    src: "{{ protofont_dest }}"
    remote_src: true
    dest: "{{ ansible_user_dir }}/.local/share/fonts/"

- name: Protofont | Source fonts
  ansible.builtin.shell:
    cmd: "fc-cache -fv"
