---
- name: "Download Proto Font"
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/0xProto.zip"
    dest: "/tmp"
    force: true
    mode: "0755"
  register: protofont

- name: "Set variable protofont_dest"
  ansible.builtin.set_fact:
    protofont_dest: "{{ protofont.dest }}"

- name: "Create font dir"
  ansible.builtin.file:
    path: "~/.local/share/fonts/"
    state: directory
    recurse: true

- name: "Unzip Proto font in ~/.local/share/fonts"
  ansible.builtin.unarchive:
    src: "{{ protofont_dest }}"
    remote_src: true
    dest: "~/.local/share/fonts/"

- name: "Source fonts"
  ansible.builtin.shell:
    cmd: "fc-cache -fv"
