---
- name: NodeJs | Using NodeJS setup script
  ansible.builtin.shell:
    cmd: "curl -fsSL https://deb.nodesource.com/setup_{{ node_version }}.x | sudo -E bash -"
  become: true

- name: NodeJs | Install Node.js
  ansible.builtin.apt:
    name:
      - nodejs
    state: present
  become: true

- name: NodeJS | Get version
  ansible.builtin.shell:
    cmd: node -v && npm -v
  register: npm_version

- name: NodeJS | Display version
  ansible.builtin.debug:
    msg: "{{ npm_version.stdout }}"

- name: NodeJS | Install Yarn
  ansible.builtin.npm:
    name: yarn
    global: true
  become: true

- name: NodeJS | Install TSNode
  ansible.builtin.npm:
    name: ts-node
    global: true
  become: true
