---
- name: "Python | Install"
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - pipx
    state: present
  become: true

- name: "Python | Ensure bpytop directory structure exists"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - ~/.config
    - ~/.config/bpytop
    - ~/.config/bpytop/themes

- name: Python | Download Catppuccin theme for bpytop
  ansible.builtin.get_url:
    url: https://github.com/catppuccin/btop/releases/download/1.0.0/themes.tar.gz
    dest: /tmp/
    mode: "0755"
  when: theme == "catppuccin"

- name: Python | Untar Catppuccin theme for bpytop
  ansible.builtin.unarchive:
    src: /tmp/themes.tar.gz
    remote_src: true
    dest: ~/.config/bpytop/
  when: theme == "catppuccin"

- name: "Python | Copy bpytop config"
  ansible.builtin.template:
    src: bpytop.conf.j2
    dest: ~/.config/bpytop/bpytop.conf
    mode: "0644"

- name: Python | Install poetry with pipx
  community.general.pipx:
    name: poetry
    python: python3
    state: present
