---
# - name: System | Update APT Repos and Upgrade APT Packages
#   ansible.builtin.apt:
#     update_cache: true
#     upgrade: safe
#     autoremove: true
#     autoclean: true
#   become: true

- name: System | Get uname -r variable
  ansible.builtin.shell:
    cmd: "uname -r"
  register: uname_cmd

- name: System | Set uname
  ansible.builtin.set_fact:
    uname: "{{ uname_cmd.stdout }}"

- name: System | Install prerequisistes
  ansible.builtin.apt:
    name:
      - build-essential
      - gnome-tweaks
      - dkms
      - "linux-headers-{{ uname }}"
      - jq
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - wget
      - xclip
      - fzf
      - fd-find
      - ripgrep
      - bat
  become: true

- name: System | Install psutil
  ansible.builtin.pip:
    name:
      - psutil

- name: System | Create ~/.local/bin folder
  ansible.builtin.file:
    state: directory
    dest: "{{ ansible_user_dir }}/.local/bin"
    mode: "0755"

- name: System | Create batsymlink
  ansible.builtin.file:
    state: link
    src: /usr/bin/batcat
    dest: "{{ ansible_user_dir }}/.local/bin/bat"
    mode: "0755"

- name: System | Set sudo
  ansible.builtin.template:
    src: user-sudo.j2
    dest: "/etc/sudoers.d/{{ ansible_env['USER'] }}"
    mode: "0644"
  become: true

- name: System | Create Background Image folder
  ansible.builtin.file:
    dest: "~/Pictures/Background"
    recurse: true
  register: background_image_folder

- name: System | Copy Desktop Background Image
  ansible.builtin.copy:
    src: dark_souls.png
    dest: "{{ background_image_folder.path }}"
    mode: "0644"
  become: true
  register: background_image

- name: System | Set Background Image uri
  ansible.builtin.set_fact:
    background_image_uri: "'file://{{ background_image.dest }}'"

- name: System | Set Desktop Background Image
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "{{ background_image_uri }}"
    state: present

- name: System | Set Caps Lock to Esc | Set fact value
  ansible.builtin.set_fact:
    xkb_options_caps_to_esc: "['grp_led:scroll', 'caps:escape_shifted_capslock']"

- name: System | Set Caps Lock to Esc | Set setting value
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "{{ xkb_options_caps_to_esc }}"
    state: present
