---
- name: ZSH | Install Zsh
  ansible.builtin.apt:
    name:
      - zsh
      - zsh-doc
  become: true

- name: ZSH | Set Zsh default shell
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    shell: /usr/bin/zsh
  become: true

- name: ZSH | Clone oh-my-zsh repo
  ansible.builtin.git:
    repo: git@github.com:ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh"
    accept_hostkey: true

- name: ZSH | Set Custom Plugins Folder
  ansible.builtin.set_fact:
    zsh_custom_plugins_folder: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins"

- name: ZSH | Clone zsh-autosuggestion
  ansible.builtin.git:
    repo: git@github.com:zsh-users/zsh-autosuggestions.git
    dest: "{{ zsh_custom_plugins_folder }}/zsh-autosuggestions"
    accept_hostkey: true

- name: ZSH | Clone zsh-completion
  ansible.builtin.git:
    repo: git@github.com:zsh-users/zsh-completions.git
    dest: "{{ zsh_custom_plugins_folder }}/zsh-completions"
    accept_hostkey: true

- name: ZSH | Clone fzf-tab-completion
  ansible.builtin.git:
    repo: git@github.com:lincheney/fzf-tab-completion.git
    dest: "{{ zsh_custom_plugins_folder }}/fzf-tab-completion"
    accept_hostkey: true

- name: ZSH | Copy zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "0600"
