---
- name: Space Bar | Smart workspaces names
  community.general.dconf:
    key: "/org/gnome/shell/extensions/space-bar/behavior/smart-workspace-names"
    value: false
    state: present

- name: Space Bar | Activate workspace shortcuts
  community.general.dconf:
    key: "/org/gnome/shell/extensions/space-bar/shortcuts/enable-activate-workspace-shortcuts"
    value: false
    state: present

- name: Space Bar | Move workspace shortcuts
  community.general.dconf:
    key: "/org/gnome/shell/extensions/space-bar/shortcuts/enable-move-to-workspace-shortcuts"
    value: true
    state: present

- name: Space Bar | Open menu
  community.general.dconf:
    key: "/org/gnome/shell/extensions/space-bar/shortcuts/open-menu"
    value: "'@as []'"
    state: present
