---
- name: Git | Install git
  ansible.builtin.apt:
    name:
      - git
  become: true

- name: Git | Include secret vars
  ansible.builtin.include_vars: secret.yml

- name: Git | Copy global template
  ansible.builtin.template:
    src: gitconfig-global
    dest: "{{ ansible_user_dir }}/.gitconfig"
    mode: "0600"

- name: Git | Create Workspace folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Workspace/"
    state: directory
    mode: "0755"

- name: Git | Create Equidia Workspace
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Workspace/Equidia"
    state: directory
    mode: "0755"

- name: Git | Copy equidia template
  ansible.builtin.template:
    src: gitconfig-equidia
    dest: "{{ ansible_user_dir }}/Workspace/Equidia/.gitconfig"
    mode: "0600"
