---
- name: Install git
  ansible.builtin.apt:
    name:
      - git
  become: true

- name: "Git | Set init.defaultBranch"
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: "Git | Set user.email"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  no_log: true

- name: "Git | Set user.name"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: Git | Set core.autocrlf
  community.general.git_config:
    name: core.autocrlf
    scope: global
    value: input
