---
- name: Go-Lang | Install GoLang Packages
  ansible.builtin.command:
    cmd: "go install {{ item.package }}"
  register: go_install
  changed_when: go_install.rc != 0
  loop_control:
    label: "{{ item.package }}"
  loop: "{{ go.packages }}"
  when: go.packages is defined
