---
- name: "Neovim | Dependencies"
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
    state: present
  become: true

- name: Neovim | Create install dir
  ansible.builtin.file:
    path: /opt/neovim
    mode: "0755"
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    state: directory
  become: true

- name: Neovim | Git clone/pull neovim latest
  ansible.builtin.git:
    repo: git@github.com:neovim/neovim.git
    dest: /opt/neovim
    force: true
    accept_hostkey: true
  register: neovim_repo

- name: Neovim | Run 'install' target as root
  community.general.make:
    chdir: "/opt/neovim"
    target: install
  become: true

- name: Neovim | Get config from my neovim repo
  ansible.builtin.git:
    repo: git@github.com:NicoGGG/nvim.git
    dest: "{{ ansible_user_dir }}/.config/nvim"
    accept_hostkey: true
